### PR TITLE
Add group work from meeting on 2021-4-13

### PR DESCRIPTION
**Pull request by oldwomanjosiah**
Contains two commits:
- Add User Model
  - Encapsulates the data for all three types of user of our application
  - Added to admin panel
  - Migrations auto generated
- Add login and base templates
  - Pulls bootstrap into the project using a base template on top of which all other templates are built
  - Login template has basic username and password form,  
    does not currently use bootstrap theming so will not be consistent with the rest of the application

### CODE REVIEW

**Review by lnahnan — APPROVED** [review]
So far so good. We will need to check how the Super User impacts the class diagram, and our code here needs to begin to think about foreign keys.

**Comment by oldwomanjosiah** [comment]
[Create Base Template](https://trello.com/c/NblduJ7B/19-create-base-template)

**Comment by oldwomanjosiah** [comment]
[Create log in page](https://trello.com/c/q0jjmaU4/16-create-log-in-page)

**Review by Imholt — APPROVED** [review]
Looks good from what I've looked through

**Pull request merged**
